# Generated by Django 3.2 on 2021-05-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_size'),
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='cart_items', through='carts.CartItem', to='items.Item', verbose_name='продуткы'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='carts.cart', verbose_name='корзина'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена'),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='carts_cart_items_items',
        ),
    ]
