# Generated by Django 3.2 on 2021-05-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210516_1724'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
    ]
