# Generated by Django 3.2 on 2021-04-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='наименование')),
                ('description', models.TextField(max_length=3000, verbose_name='описание')),
                ('image', models.ImageField(upload_to='items', verbose_name='картинка')),
                ('weight', models.PositiveIntegerField(verbose_name='вес в граммах')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена в рублях')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Коробка',
                'verbose_name_plural': 'Коробки',
            },
        ),
    ]
