# Generated by Django 3.2 on 2021-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='текст отзыва')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('published_at', models.DateTimeField(null=True, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('на модерации', 'New'), ('опубликован', 'Published'), ('отклонен', 'Hidden')], default='на модерации', max_length=30)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
