# Generated by Django 3.2 on 2021-04-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(choices=[('на модерации', 'New'), ('опубликован', 'Published'), ('отклонен', 'Hidden')], default='на модерации', max_length=30),
        ),
    ]
