# Generated by Django 3.2 on 2021-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.CharField(choices=[('на модерации', 'On Moderation'), ('опубликован', 'Published'), ('отклонен', 'Rejected')], default='на модерации', max_length=30),
        ),
    ]
