# Generated by Django 3.2 on 2021-05-09 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('delivery_at', models.DateTimeField(verbose_name='Дата доставки')),
                ('address', models.CharField(max_length=60, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('created', 'Created'), ('delivered', 'Delivered'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='created', max_length=40, verbose_name='Статус')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='carts.cart', verbose_name='Корзина')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
